[package]
name = "os"
version = "0.1.0"
authors = ["Campbell He <hkp18@mails.tsinghua.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
customizable-buddy = "0.0.2"
buddy_system_allocator = "0.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = "0.4"
riscv = { git = "https://github.com/duskmoon314/riscv", branch = "extN", features = [
    "inline-asm",
] }
spin = { version = "0.9", features = ["use_ticket_mutex"] }
xmas-elf = "0.7.0"
rv-plic = { git = "https://github.com/duskmoon314/rv-plic" }
# uart8250 = { version = "*", features = ["fmt"], optional = true }
uart8250 = { version = "0.5.0", features = ["fmt"], optional = true }
uart_xilinx = { version = "*", features = ["fmt"], optional = true }
embedded-hal = "=1.0.0-alpha.4"
nb = "1.0.0"
array-init = "2.0.0"
heapless = "0.7.5"
lib_so = { path = "../lib_so" }


[features]
board_qemu = ["uart8250"]
board_lrv = ["uart_xilinx"]

default = ["board_qemu"]

[build-dependencies]
serde_derive = "1.0"
serde = "1.0"
toml = "0.5.9"


