[package]
name = "user_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
customizable-buddy = "0.0.2"

lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
riscv = { git = "https://github.com/duskmoon314/riscv", branch = "extN", features = [
    "inline-asm",
] }
spin = { version = "0.9", features = ["use_ticket_mutex"] }
rv-plic = { git = "https://github.com/duskmoon314/rv-plic" }
# uart8250 = { version = "*", features = ["fmt"], optional = true }
uart8250 = { version = "0.5.0", features = ["fmt"], optional = true }
uart_xilinx = { version = "*", features = ["fmt"], optional = true }
embedded-hal = "=1.0.0-alpha.4"
nb = "1.0.0"
array-init = "2.0.0"
rand_xorshift = "0.3.0"
rand_core = "0.6.3"
heapless = "0.7.5"
blake2 = { version = "0.10", default-features = false }
blake3 = { version = "1.2.0", default-features = false }
sha2 = { version = "0.10", default-features = false }
unifi-exposure = { path = "../unifi-exposure" }
syscall = { path = "../syscall", features = ["user"] }

[features]
board_qemu = ["uart8250"]
board_lrv = ["uart_xilinx"]
