cpu_load
flush
flush_trace
forktest
threads
threads_arg
hello_world
hello_world_simple
initproc
ipc_benchmark
ipc_load
loop_spawn_test
spawn_test
uart_benchmark
uart_ext
uart_load
ub_loop
user_trap_demo
unfi-sche
user_timer